spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: jwtsms
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
server:
  port: 8888

jwt:
  secret: ${JWT_SECRET}
  lifetime: 30s

logging:
  level:
    org:
      springframework:
        security: DEBUG